### ISSUE TITLE
Slider freeze

### ISSUE THREAD

**Issue by mikhailovenator** [joseluisq/slendr#114]
## Expected Behavior
Should navigate to next/prev slide
...

## Actual Behavior
Can't navigate to next/prev slide
...

## Steps to Reproduce the Problem

  1. Open page with slider with slideshow.
  2. Activate another tab for some time (1-2min enough actually I think period of time between slides)

  requestAnimationFrame is not called in most browsers when running in background tabs. So animating = true forever.

This code doesn't work any more after this: 

function prev() {
        if (animating)
            return;
        moveTo('prev');
    }
    function next() {
        if (animating)
            return;
        moveTo('next');
    }
function goTo(i) {
        if (!animating && current !== i && (i >= 0 && i < slides.length)) {
            moveTo(current - i < 0 ? 'next' : 'prev', i);
        }
    }

**Comment by joseluisq** [comment]
Thanks to report. Yeah this is already solved at https://github.com/joseluisq/slendr/pull/113
Stay tunned to the next release today.

**Comment by joseluisq** [comment]
Done [v1.3.0](https://github.com/joseluisq/slendr/releases/tag/v1.3.0)

**Comment by mikhailovenator** [comment]
Great! Thank you.
