### ISSUE TITLE
React support

### ISSUE THREAD

**Issue by joseluisq** [joseluisq/slendr#35]
For example: `react-slendr`

- [ ] Now, in development process https://github.com/joseluisq/react-slendr

**Comment by xRahul** [comment]
Hey @joseluisq 

I can work on it. I've been looking forward to wrapping on of these kind of projects as react compoents. let me know if you're interested

**Comment by joseluisq** [comment]
@xRahul fine. Hands on code!  :+1:

**Comment by joseluisq** [comment]
Now, in development process https://github.com/joseluisq/react-slendr

**Comment by joseluisq** [comment]
@xRahul are you still interested in work on this component too?
The repository: https://github.com/joseluisq/react-slendr
Here you have an idea for project structure: https://github.com/joseluisq/react-prelodr
