### ISSUE TITLE
Object.assign not working with IE11

### ISSUE THREAD

**Issue by loudoweb** [joseluisq/slendr#88]
https://github.com/joseluisq/slendr/blob/master/src/index.js#L12

**Object.assign for IE11**

IE11 needs another method to merge the data between the two objects because the method doesn't exist in this browser.

**Comment by joseluisq** [comment]
Yep, It could add a [object-assign](https://www.npmjs.com/package/object-assign) polyfill.
PR is welcome! :smile:

**Comment by joseluisq** [comment]
Done in [v1.1.7](https://github.com/joseluisq/slendr/releases/tag/v1.1.7)!
